package constUser

const (
	USER_STATUS_ONLINE  = 1
	USER_STATUS_OFFLINE = 2
)

const (
	USER_HERO_MAIN_INDEX   = 1 //主角
	USER_HERO_SECOND_INDEX = 2 //主角
	USER_HERO_THREE_INDEX  = 3 //主角
)

var (
	USER_HERO_INDEX = []int{USER_HERO_MAIN_INDEX, USER_HERO_SECOND_INDEX, USER_HERO_THREE_INDEX}
)

const ACCOUNT_BAN_KEY = 0

const (
	BAN_TYPE_LOGIIN = 1
	BAN_TYPE_CHAT   = 2
)

const (
	VIP_CUSTOMER_LOOK_NO  = 0
	VIP_CUSTOMER_LOOK_YES = 1
)
