// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fieldFight.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 野战load
type FieldFightLoadReq struct {
}

func (m *FieldFightLoadReq) Reset()                    { *m = FieldFightLoadReq{} }
func (m *FieldFightLoadReq) String() string            { return proto.CompactTextString(m) }
func (*FieldFightLoadReq) ProtoMessage()               {}
func (*FieldFightLoadReq) Descriptor() ([]byte, []int) { return fileDescriptorFieldFight, []int{0} }

type FieldFightLoadAck struct {
	ListInfo             []*FieldFightListInfo         `protobuf:"bytes,1,rep,name=listInfo" json:"listInfo,omitempty"`
	MyCombat             int32                         `protobuf:"varint,2,opt,name=myCombat,proto3" json:"myCombat,omitempty"`
	RemainChallengeTimes int32                         `protobuf:"varint,3,opt,name=remainChallengeTimes,proto3" json:"remainChallengeTimes,omitempty"`
	TodayCanBuyTimes     int32                         `protobuf:"varint,4,opt,name=todayCanBuyTimes,proto3" json:"todayCanBuyTimes,omitempty"`
	ChangeRivalCd        int32                         `protobuf:"varint,5,opt,name=changeRivalCd,proto3" json:"changeRivalCd,omitempty"`
	BeatBackOwnUserInfo  []*FieldFightBeatBackUserInfo `protobuf:"bytes,6,rep,name=BeatBackOwnUserInfo" json:"BeatBackOwnUserInfo,omitempty"`
	IsCheckNoPromptState int32                         `protobuf:"varint,7,opt,name=isCheckNoPromptState,proto3" json:"isCheckNoPromptState,omitempty"`
}

func (m *FieldFightLoadAck) Reset()                    { *m = FieldFightLoadAck{} }
func (m *FieldFightLoadAck) String() string            { return proto.CompactTextString(m) }
func (*FieldFightLoadAck) ProtoMessage()               {}
func (*FieldFightLoadAck) Descriptor() ([]byte, []int) { return fileDescriptorFieldFight, []int{1} }

func (m *FieldFightLoadAck) GetListInfo() []*FieldFightListInfo {
	if m != nil {
		return m.ListInfo
	}
	return nil
}

func (m *FieldFightLoadAck) GetMyCombat() int32 {
	if m != nil {
		return m.MyCombat
	}
	return 0
}

func (m *FieldFightLoadAck) GetRemainChallengeTimes() int32 {
	if m != nil {
		return m.RemainChallengeTimes
	}
	return 0
}

func (m *FieldFightLoadAck) GetTodayCanBuyTimes() int32 {
	if m != nil {
		return m.TodayCanBuyTimes
	}
	return 0
}

func (m *FieldFightLoadAck) GetChangeRivalCd() int32 {
	if m != nil {
		return m.ChangeRivalCd
	}
	return 0
}

func (m *FieldFightLoadAck) GetBeatBackOwnUserInfo() []*FieldFightBeatBackUserInfo {
	if m != nil {
		return m.BeatBackOwnUserInfo
	}
	return nil
}

func (m *FieldFightLoadAck) GetIsCheckNoPromptState() int32 {
	if m != nil {
		return m.IsCheckNoPromptState
	}
	return 0
}

// 进入战斗
type EnterFieldFightReq struct {
	ChallengeUid int32 `protobuf:"varint,1,opt,name=challengeUid,proto3" json:"challengeUid,omitempty"`
	IsBeatBack   int32 `protobuf:"varint,2,opt,name=isBeatBack,proto3" json:"isBeatBack,omitempty"`
}

func (m *EnterFieldFightReq) Reset()                    { *m = EnterFieldFightReq{} }
func (m *EnterFieldFightReq) String() string            { return proto.CompactTextString(m) }
func (*EnterFieldFightReq) ProtoMessage()               {}
func (*EnterFieldFightReq) Descriptor() ([]byte, []int) { return fileDescriptorFieldFight, []int{2} }

func (m *EnterFieldFightReq) GetChallengeUid() int32 {
	if m != nil {
		return m.ChallengeUid
	}
	return 0
}

func (m *EnterFieldFightReq) GetIsBeatBack() int32 {
	if m != nil {
		return m.IsBeatBack
	}
	return 0
}

type FieldFightNtf struct {
	Result               int32                         `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Goods                *GoodsChangeNtf               `protobuf:"bytes,2,opt,name=goods" json:"goods,omitempty"`
	RemainChallengeTimes int32                         `protobuf:"varint,3,opt,name=remainChallengeTimes,proto3" json:"remainChallengeTimes,omitempty"`
	ListInfo             []*FieldFightListInfo         `protobuf:"bytes,4,rep,name=listInfo" json:"listInfo,omitempty"`
	BeatBackOwnUserInfo  []*FieldFightBeatBackUserInfo `protobuf:"bytes,5,rep,name=BeatBackOwnUserInfo" json:"BeatBackOwnUserInfo,omitempty"`
}

func (m *FieldFightNtf) Reset()                    { *m = FieldFightNtf{} }
func (m *FieldFightNtf) String() string            { return proto.CompactTextString(m) }
func (*FieldFightNtf) ProtoMessage()               {}
func (*FieldFightNtf) Descriptor() ([]byte, []int) { return fileDescriptorFieldFight, []int{3} }

func (m *FieldFightNtf) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *FieldFightNtf) GetGoods() *GoodsChangeNtf {
	if m != nil {
		return m.Goods
	}
	return nil
}

func (m *FieldFightNtf) GetRemainChallengeTimes() int32 {
	if m != nil {
		return m.RemainChallengeTimes
	}
	return 0
}

func (m *FieldFightNtf) GetListInfo() []*FieldFightListInfo {
	if m != nil {
		return m.ListInfo
	}
	return nil
}

func (m *FieldFightNtf) GetBeatBackOwnUserInfo() []*FieldFightBeatBackUserInfo {
	if m != nil {
		return m.BeatBackOwnUserInfo
	}
	return nil
}

// 挑战次数购买
type BuyFieldFightChallengeTimesReq struct {
}

func (m *BuyFieldFightChallengeTimesReq) Reset()         { *m = BuyFieldFightChallengeTimesReq{} }
func (m *BuyFieldFightChallengeTimesReq) String() string { return proto.CompactTextString(m) }
func (*BuyFieldFightChallengeTimesReq) ProtoMessage()    {}
func (*BuyFieldFightChallengeTimesReq) Descriptor() ([]byte, []int) {
	return fileDescriptorFieldFight, []int{4}
}

type BuyFieldFightChallengeTimesAck struct {
	ResidueTimes     int32 `protobuf:"varint,1,opt,name=residueTimes,proto3" json:"residueTimes,omitempty"`
	TodayCanBuyTimes int32 `protobuf:"varint,2,opt,name=todayCanBuyTimes,proto3" json:"todayCanBuyTimes,omitempty"`
}

func (m *BuyFieldFightChallengeTimesAck) Reset()         { *m = BuyFieldFightChallengeTimesAck{} }
func (m *BuyFieldFightChallengeTimesAck) String() string { return proto.CompactTextString(m) }
func (*BuyFieldFightChallengeTimesAck) ProtoMessage()    {}
func (*BuyFieldFightChallengeTimesAck) Descriptor() ([]byte, []int) {
	return fileDescriptorFieldFight, []int{5}
}

func (m *BuyFieldFightChallengeTimesAck) GetResidueTimes() int32 {
	if m != nil {
		return m.ResidueTimes
	}
	return 0
}

func (m *BuyFieldFightChallengeTimesAck) GetTodayCanBuyTimes() int32 {
	if m != nil {
		return m.TodayCanBuyTimes
	}
	return 0
}

// 刷新对手
type RefFieldFightRivalUserReq struct {
}

func (m *RefFieldFightRivalUserReq) Reset()         { *m = RefFieldFightRivalUserReq{} }
func (m *RefFieldFightRivalUserReq) String() string { return proto.CompactTextString(m) }
func (*RefFieldFightRivalUserReq) ProtoMessage()    {}
func (*RefFieldFightRivalUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptorFieldFight, []int{6}
}

type RefFieldFightRivalUserAck struct {
	ListInfo      []*FieldFightListInfo `protobuf:"bytes,1,rep,name=listInfo" json:"listInfo,omitempty"`
	ChangeRivalCd int32                 `protobuf:"varint,2,opt,name=changeRivalCd,proto3" json:"changeRivalCd,omitempty"`
}

func (m *RefFieldFightRivalUserAck) Reset()         { *m = RefFieldFightRivalUserAck{} }
func (m *RefFieldFightRivalUserAck) String() string { return proto.CompactTextString(m) }
func (*RefFieldFightRivalUserAck) ProtoMessage()    {}
func (*RefFieldFightRivalUserAck) Descriptor() ([]byte, []int) {
	return fileDescriptorFieldFight, []int{7}
}

func (m *RefFieldFightRivalUserAck) GetListInfo() []*FieldFightListInfo {
	if m != nil {
		return m.ListInfo
	}
	return nil
}

func (m *RefFieldFightRivalUserAck) GetChangeRivalCd() int32 {
	if m != nil {
		return m.ChangeRivalCd
	}
	return 0
}

type FieldFightListInfo struct {
	DifficultyLevel int32       `protobuf:"varint,1,opt,name=difficultyLevel,proto3" json:"difficultyLevel,omitempty"`
	Avatar          string      `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	NickName        string      `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Combat          int32       `protobuf:"varint,4,opt,name=combat,proto3" json:"combat,omitempty"`
	UserLv          int32       `protobuf:"varint,5,opt,name=userLv,proto3" json:"userLv,omitempty"`
	RewardInfos     []*ItemUnit `protobuf:"bytes,6,rep,name=rewardInfos" json:"rewardInfos,omitempty"`
	UserId          int32       `protobuf:"varint,7,opt,name=userId,proto3" json:"userId,omitempty"`
	Job             int32       `protobuf:"varint,8,opt,name=job,proto3" json:"job,omitempty"`
	Sex             int32       `protobuf:"varint,9,opt,name=sex,proto3" json:"sex,omitempty"`
}

func (m *FieldFightListInfo) Reset()                    { *m = FieldFightListInfo{} }
func (m *FieldFightListInfo) String() string            { return proto.CompactTextString(m) }
func (*FieldFightListInfo) ProtoMessage()               {}
func (*FieldFightListInfo) Descriptor() ([]byte, []int) { return fileDescriptorFieldFight, []int{8} }

func (m *FieldFightListInfo) GetDifficultyLevel() int32 {
	if m != nil {
		return m.DifficultyLevel
	}
	return 0
}

func (m *FieldFightListInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *FieldFightListInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *FieldFightListInfo) GetCombat() int32 {
	if m != nil {
		return m.Combat
	}
	return 0
}

func (m *FieldFightListInfo) GetUserLv() int32 {
	if m != nil {
		return m.UserLv
	}
	return 0
}

func (m *FieldFightListInfo) GetRewardInfos() []*ItemUnit {
	if m != nil {
		return m.RewardInfos
	}
	return nil
}

func (m *FieldFightListInfo) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FieldFightListInfo) GetJob() int32 {
	if m != nil {
		return m.Job
	}
	return 0
}

func (m *FieldFightListInfo) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

type FieldFightBeatBackUserInfo struct {
	UserId   int32  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	NickName string `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
}

func (m *FieldFightBeatBackUserInfo) Reset()         { *m = FieldFightBeatBackUserInfo{} }
func (m *FieldFightBeatBackUserInfo) String() string { return proto.CompactTextString(m) }
func (*FieldFightBeatBackUserInfo) ProtoMessage()    {}
func (*FieldFightBeatBackUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptorFieldFight, []int{9}
}

func (m *FieldFightBeatBackUserInfo) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FieldFightBeatBackUserInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

type BeatBackInfoNtf struct {
	BeatBackOwnUserInfo []*FieldFightBeatBackUserInfo `protobuf:"bytes,1,rep,name=BeatBackOwnUserInfo" json:"BeatBackOwnUserInfo,omitempty"`
}

func (m *BeatBackInfoNtf) Reset()                    { *m = BeatBackInfoNtf{} }
func (m *BeatBackInfoNtf) String() string            { return proto.CompactTextString(m) }
func (*BeatBackInfoNtf) ProtoMessage()               {}
func (*BeatBackInfoNtf) Descriptor() ([]byte, []int) { return fileDescriptorFieldFight, []int{10} }

func (m *BeatBackInfoNtf) GetBeatBackOwnUserInfo() []*FieldFightBeatBackUserInfo {
	if m != nil {
		return m.BeatBackOwnUserInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*FieldFightLoadReq)(nil), "pb.FieldFightLoadReq")
	proto.RegisterType((*FieldFightLoadAck)(nil), "pb.FieldFightLoadAck")
	proto.RegisterType((*EnterFieldFightReq)(nil), "pb.EnterFieldFightReq")
	proto.RegisterType((*FieldFightNtf)(nil), "pb.FieldFightNtf")
	proto.RegisterType((*BuyFieldFightChallengeTimesReq)(nil), "pb.BuyFieldFightChallengeTimesReq")
	proto.RegisterType((*BuyFieldFightChallengeTimesAck)(nil), "pb.BuyFieldFightChallengeTimesAck")
	proto.RegisterType((*RefFieldFightRivalUserReq)(nil), "pb.RefFieldFightRivalUserReq")
	proto.RegisterType((*RefFieldFightRivalUserAck)(nil), "pb.RefFieldFightRivalUserAck")
	proto.RegisterType((*FieldFightListInfo)(nil), "pb.FieldFightListInfo")
	proto.RegisterType((*FieldFightBeatBackUserInfo)(nil), "pb.FieldFightBeatBackUserInfo")
	proto.RegisterType((*BeatBackInfoNtf)(nil), "pb.BeatBackInfoNtf")
}
func (m *FieldFightLoadReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FieldFightLoadReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *FieldFightLoadAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FieldFightLoadAck) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ListInfo) > 0 {
		for _, msg := range m.ListInfo {
			dAtA[i] = 0xa
			i++
			i = encodeVarintFieldFight(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.MyCombat != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.MyCombat))
	}
	if m.RemainChallengeTimes != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.RemainChallengeTimes))
	}
	if m.TodayCanBuyTimes != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.TodayCanBuyTimes))
	}
	if m.ChangeRivalCd != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.ChangeRivalCd))
	}
	if len(m.BeatBackOwnUserInfo) > 0 {
		for _, msg := range m.BeatBackOwnUserInfo {
			dAtA[i] = 0x32
			i++
			i = encodeVarintFieldFight(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.IsCheckNoPromptState != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.IsCheckNoPromptState))
	}
	return i, nil
}

func (m *EnterFieldFightReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EnterFieldFightReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ChallengeUid != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.ChallengeUid))
	}
	if m.IsBeatBack != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.IsBeatBack))
	}
	return i, nil
}

func (m *FieldFightNtf) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FieldFightNtf) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Result != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.Result))
	}
	if m.Goods != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.Goods.Size()))
		n1, err := m.Goods.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.RemainChallengeTimes != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.RemainChallengeTimes))
	}
	if len(m.ListInfo) > 0 {
		for _, msg := range m.ListInfo {
			dAtA[i] = 0x22
			i++
			i = encodeVarintFieldFight(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.BeatBackOwnUserInfo) > 0 {
		for _, msg := range m.BeatBackOwnUserInfo {
			dAtA[i] = 0x2a
			i++
			i = encodeVarintFieldFight(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *BuyFieldFightChallengeTimesReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BuyFieldFightChallengeTimesReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *BuyFieldFightChallengeTimesAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BuyFieldFightChallengeTimesAck) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ResidueTimes != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.ResidueTimes))
	}
	if m.TodayCanBuyTimes != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.TodayCanBuyTimes))
	}
	return i, nil
}

func (m *RefFieldFightRivalUserReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RefFieldFightRivalUserReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *RefFieldFightRivalUserAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RefFieldFightRivalUserAck) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ListInfo) > 0 {
		for _, msg := range m.ListInfo {
			dAtA[i] = 0xa
			i++
			i = encodeVarintFieldFight(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.ChangeRivalCd != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.ChangeRivalCd))
	}
	return i, nil
}

func (m *FieldFightListInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FieldFightListInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.DifficultyLevel != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.DifficultyLevel))
	}
	if len(m.Avatar) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(len(m.Avatar)))
		i += copy(dAtA[i:], m.Avatar)
	}
	if len(m.NickName) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(len(m.NickName)))
		i += copy(dAtA[i:], m.NickName)
	}
	if m.Combat != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.Combat))
	}
	if m.UserLv != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.UserLv))
	}
	if len(m.RewardInfos) > 0 {
		for _, msg := range m.RewardInfos {
			dAtA[i] = 0x32
			i++
			i = encodeVarintFieldFight(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.UserId != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.UserId))
	}
	if m.Job != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.Job))
	}
	if m.Sex != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.Sex))
	}
	return i, nil
}

func (m *FieldFightBeatBackUserInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FieldFightBeatBackUserInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.UserId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(m.UserId))
	}
	if len(m.NickName) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintFieldFight(dAtA, i, uint64(len(m.NickName)))
		i += copy(dAtA[i:], m.NickName)
	}
	return i, nil
}

func (m *BeatBackInfoNtf) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BeatBackInfoNtf) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.BeatBackOwnUserInfo) > 0 {
		for _, msg := range m.BeatBackOwnUserInfo {
			dAtA[i] = 0xa
			i++
			i = encodeVarintFieldFight(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func encodeVarintFieldFight(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *FieldFightLoadReq) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *FieldFightLoadAck) Size() (n int) {
	var l int
	_ = l
	if len(m.ListInfo) > 0 {
		for _, e := range m.ListInfo {
			l = e.Size()
			n += 1 + l + sovFieldFight(uint64(l))
		}
	}
	if m.MyCombat != 0 {
		n += 1 + sovFieldFight(uint64(m.MyCombat))
	}
	if m.RemainChallengeTimes != 0 {
		n += 1 + sovFieldFight(uint64(m.RemainChallengeTimes))
	}
	if m.TodayCanBuyTimes != 0 {
		n += 1 + sovFieldFight(uint64(m.TodayCanBuyTimes))
	}
	if m.ChangeRivalCd != 0 {
		n += 1 + sovFieldFight(uint64(m.ChangeRivalCd))
	}
	if len(m.BeatBackOwnUserInfo) > 0 {
		for _, e := range m.BeatBackOwnUserInfo {
			l = e.Size()
			n += 1 + l + sovFieldFight(uint64(l))
		}
	}
	if m.IsCheckNoPromptState != 0 {
		n += 1 + sovFieldFight(uint64(m.IsCheckNoPromptState))
	}
	return n
}

func (m *EnterFieldFightReq) Size() (n int) {
	var l int
	_ = l
	if m.ChallengeUid != 0 {
		n += 1 + sovFieldFight(uint64(m.ChallengeUid))
	}
	if m.IsBeatBack != 0 {
		n += 1 + sovFieldFight(uint64(m.IsBeatBack))
	}
	return n
}

func (m *FieldFightNtf) Size() (n int) {
	var l int
	_ = l
	if m.Result != 0 {
		n += 1 + sovFieldFight(uint64(m.Result))
	}
	if m.Goods != nil {
		l = m.Goods.Size()
		n += 1 + l + sovFieldFight(uint64(l))
	}
	if m.RemainChallengeTimes != 0 {
		n += 1 + sovFieldFight(uint64(m.RemainChallengeTimes))
	}
	if len(m.ListInfo) > 0 {
		for _, e := range m.ListInfo {
			l = e.Size()
			n += 1 + l + sovFieldFight(uint64(l))
		}
	}
	if len(m.BeatBackOwnUserInfo) > 0 {
		for _, e := range m.BeatBackOwnUserInfo {
			l = e.Size()
			n += 1 + l + sovFieldFight(uint64(l))
		}
	}
	return n
}

func (m *BuyFieldFightChallengeTimesReq) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *BuyFieldFightChallengeTimesAck) Size() (n int) {
	var l int
	_ = l
	if m.ResidueTimes != 0 {
		n += 1 + sovFieldFight(uint64(m.ResidueTimes))
	}
	if m.TodayCanBuyTimes != 0 {
		n += 1 + sovFieldFight(uint64(m.TodayCanBuyTimes))
	}
	return n
}

func (m *RefFieldFightRivalUserReq) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *RefFieldFightRivalUserAck) Size() (n int) {
	var l int
	_ = l
	if len(m.ListInfo) > 0 {
		for _, e := range m.ListInfo {
			l = e.Size()
			n += 1 + l + sovFieldFight(uint64(l))
		}
	}
	if m.ChangeRivalCd != 0 {
		n += 1 + sovFieldFight(uint64(m.ChangeRivalCd))
	}
	return n
}

func (m *FieldFightListInfo) Size() (n int) {
	var l int
	_ = l
	if m.DifficultyLevel != 0 {
		n += 1 + sovFieldFight(uint64(m.DifficultyLevel))
	}
	l = len(m.Avatar)
	if l > 0 {
		n += 1 + l + sovFieldFight(uint64(l))
	}
	l = len(m.NickName)
	if l > 0 {
		n += 1 + l + sovFieldFight(uint64(l))
	}
	if m.Combat != 0 {
		n += 1 + sovFieldFight(uint64(m.Combat))
	}
	if m.UserLv != 0 {
		n += 1 + sovFieldFight(uint64(m.UserLv))
	}
	if len(m.RewardInfos) > 0 {
		for _, e := range m.RewardInfos {
			l = e.Size()
			n += 1 + l + sovFieldFight(uint64(l))
		}
	}
	if m.UserId != 0 {
		n += 1 + sovFieldFight(uint64(m.UserId))
	}
	if m.Job != 0 {
		n += 1 + sovFieldFight(uint64(m.Job))
	}
	if m.Sex != 0 {
		n += 1 + sovFieldFight(uint64(m.Sex))
	}
	return n
}

func (m *FieldFightBeatBackUserInfo) Size() (n int) {
	var l int
	_ = l
	if m.UserId != 0 {
		n += 1 + sovFieldFight(uint64(m.UserId))
	}
	l = len(m.NickName)
	if l > 0 {
		n += 1 + l + sovFieldFight(uint64(l))
	}
	return n
}

func (m *BeatBackInfoNtf) Size() (n int) {
	var l int
	_ = l
	if len(m.BeatBackOwnUserInfo) > 0 {
		for _, e := range m.BeatBackOwnUserInfo {
			l = e.Size()
			n += 1 + l + sovFieldFight(uint64(l))
		}
	}
	return n
}

func sovFieldFight(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozFieldFight(x uint64) (n int) {
	return sovFieldFight(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FieldFightLoadReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFieldFight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FieldFightLoadReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FieldFightLoadReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipFieldFight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFieldFight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FieldFightLoadAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFieldFight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FieldFightLoadAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FieldFightLoadAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFieldFight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ListInfo = append(m.ListInfo, &FieldFightListInfo{})
			if err := m.ListInfo[len(m.ListInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MyCombat", wireType)
			}
			m.MyCombat = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MyCombat |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainChallengeTimes", wireType)
			}
			m.RemainChallengeTimes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainChallengeTimes |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TodayCanBuyTimes", wireType)
			}
			m.TodayCanBuyTimes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TodayCanBuyTimes |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChangeRivalCd", wireType)
			}
			m.ChangeRivalCd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChangeRivalCd |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeatBackOwnUserInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFieldFight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BeatBackOwnUserInfo = append(m.BeatBackOwnUserInfo, &FieldFightBeatBackUserInfo{})
			if err := m.BeatBackOwnUserInfo[len(m.BeatBackOwnUserInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsCheckNoPromptState", wireType)
			}
			m.IsCheckNoPromptState = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IsCheckNoPromptState |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFieldFight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFieldFight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EnterFieldFightReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFieldFight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EnterFieldFightReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EnterFieldFightReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeUid", wireType)
			}
			m.ChallengeUid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengeUid |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsBeatBack", wireType)
			}
			m.IsBeatBack = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IsBeatBack |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFieldFight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFieldFight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FieldFightNtf) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFieldFight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FieldFightNtf: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FieldFightNtf: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			m.Result = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Result |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Goods", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFieldFight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Goods == nil {
				m.Goods = &GoodsChangeNtf{}
			}
			if err := m.Goods.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainChallengeTimes", wireType)
			}
			m.RemainChallengeTimes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainChallengeTimes |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFieldFight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ListInfo = append(m.ListInfo, &FieldFightListInfo{})
			if err := m.ListInfo[len(m.ListInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeatBackOwnUserInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFieldFight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BeatBackOwnUserInfo = append(m.BeatBackOwnUserInfo, &FieldFightBeatBackUserInfo{})
			if err := m.BeatBackOwnUserInfo[len(m.BeatBackOwnUserInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFieldFight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFieldFight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BuyFieldFightChallengeTimesReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFieldFight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BuyFieldFightChallengeTimesReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BuyFieldFightChallengeTimesReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipFieldFight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFieldFight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BuyFieldFightChallengeTimesAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFieldFight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BuyFieldFightChallengeTimesAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BuyFieldFightChallengeTimesAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResidueTimes", wireType)
			}
			m.ResidueTimes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResidueTimes |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TodayCanBuyTimes", wireType)
			}
			m.TodayCanBuyTimes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TodayCanBuyTimes |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFieldFight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFieldFight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RefFieldFightRivalUserReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFieldFight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RefFieldFightRivalUserReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RefFieldFightRivalUserReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipFieldFight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFieldFight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RefFieldFightRivalUserAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFieldFight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RefFieldFightRivalUserAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RefFieldFightRivalUserAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFieldFight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ListInfo = append(m.ListInfo, &FieldFightListInfo{})
			if err := m.ListInfo[len(m.ListInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChangeRivalCd", wireType)
			}
			m.ChangeRivalCd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChangeRivalCd |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFieldFight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFieldFight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FieldFightListInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFieldFight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FieldFightListInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FieldFightListInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DifficultyLevel", wireType)
			}
			m.DifficultyLevel = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DifficultyLevel |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Avatar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFieldFight
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Avatar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NickName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFieldFight
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NickName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Combat", wireType)
			}
			m.Combat = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Combat |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserLv", wireType)
			}
			m.UserLv = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserLv |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardInfos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFieldFight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardInfos = append(m.RewardInfos, &ItemUnit{})
			if err := m.RewardInfos[len(m.RewardInfos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			m.UserId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserId |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Job", wireType)
			}
			m.Job = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Job |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sex", wireType)
			}
			m.Sex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sex |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFieldFight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFieldFight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FieldFightBeatBackUserInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFieldFight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FieldFightBeatBackUserInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FieldFightBeatBackUserInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			m.UserId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserId |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NickName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFieldFight
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NickName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFieldFight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFieldFight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BeatBackInfoNtf) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFieldFight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BeatBackInfoNtf: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BeatBackInfoNtf: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeatBackOwnUserInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFieldFight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BeatBackOwnUserInfo = append(m.BeatBackOwnUserInfo, &FieldFightBeatBackUserInfo{})
			if err := m.BeatBackOwnUserInfo[len(m.BeatBackOwnUserInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFieldFight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFieldFight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFieldFight(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFieldFight
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFieldFight
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthFieldFight
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowFieldFight
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipFieldFight(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthFieldFight = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFieldFight   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("fieldFight.proto", fileDescriptorFieldFight) }

var fileDescriptorFieldFight = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x41, 0x6e, 0xd3, 0x40,
	0x14, 0xc5, 0x6e, 0x53, 0xda, 0xdf, 0x54, 0x0d, 0x53, 0x54, 0x99, 0x22, 0x59, 0x95, 0xc5, 0x22,
	0x62, 0x91, 0x45, 0x38, 0x01, 0x89, 0x28, 0xaa, 0x54, 0x85, 0xca, 0x50, 0x89, 0xed, 0xc4, 0xfe,
	0x4e, 0x86, 0xd8, 0x9e, 0xd4, 0x33, 0x4e, 0x9b, 0x33, 0x20, 0xb1, 0xe6, 0x48, 0x2c, 0x39, 0x02,
	0x2a, 0x07, 0xe0, 0x0a, 0x68, 0xc6, 0xe3, 0xd4, 0x6e, 0x1d, 0x84, 0xb2, 0xcb, 0x7f, 0xf3, 0xfc,
	0xf2, 0xdf, 0xfc, 0xf7, 0x07, 0x3a, 0x11, 0xc3, 0x38, 0x3c, 0x63, 0x93, 0xa9, 0xec, 0xcd, 0x33,
	0x2e, 0x39, 0xb1, 0xe7, 0xe3, 0x93, 0x76, 0xc0, 0x93, 0x84, 0xa7, 0x05, 0xe2, 0x1d, 0xc1, 0xb3,
	0xb3, 0x15, 0xeb, 0x82, 0xd3, 0xd0, 0xc7, 0x6b, 0xef, 0x8f, 0xfd, 0x10, 0x7d, 0x1b, 0xcc, 0x48,
	0x1f, 0x76, 0x63, 0x26, 0xe4, 0x79, 0x1a, 0x71, 0xc7, 0x3a, 0xdd, 0xea, 0xee, 0xf7, 0x8f, 0x7b,
	0xf3, 0x71, 0xaf, 0x42, 0x34, 0xa7, 0xfe, 0x8a, 0x47, 0x4e, 0x60, 0x37, 0x59, 0x0e, 0x79, 0x32,
	0xa6, 0xd2, 0xb1, 0x4f, 0xad, 0x6e, 0xcb, 0x5f, 0xd5, 0xa4, 0x0f, 0xcf, 0x33, 0x4c, 0x28, 0x4b,
	0x87, 0x53, 0x1a, 0xc7, 0x98, 0x4e, 0xf0, 0x13, 0x4b, 0x50, 0x38, 0x5b, 0x9a, 0xd7, 0x78, 0x46,
	0x5e, 0x43, 0x47, 0xf2, 0x90, 0x2e, 0x87, 0x34, 0x1d, 0xe4, 0xcb, 0x82, 0xbf, 0xad, 0xf9, 0x8f,
	0x70, 0xf2, 0x0a, 0x0e, 0x82, 0x29, 0x4d, 0x27, 0xe8, 0xb3, 0x05, 0x8d, 0x87, 0xa1, 0xd3, 0xd2,
	0xc4, 0x3a, 0x48, 0x2e, 0xe1, 0x68, 0x80, 0x54, 0x0e, 0x68, 0x30, 0xfb, 0x70, 0x93, 0x5e, 0x09,
	0xcc, 0xb4, 0xc1, 0x1d, 0x6d, 0xd0, 0xad, 0x1b, 0x2c, 0x89, 0x25, 0xcb, 0x6f, 0xfa, 0x54, 0xf9,
	0x62, 0x62, 0x38, 0xc5, 0x60, 0x36, 0xe2, 0x97, 0x19, 0x4f, 0xe6, 0xf2, 0xa3, 0xa4, 0x12, 0x9d,
	0xa7, 0x85, 0xaf, 0xa6, 0x33, 0xef, 0x33, 0x90, 0x77, 0xa9, 0xc4, 0xec, 0xfe, 0xbf, 0x7c, 0xbc,
	0x26, 0x1e, 0xb4, 0x83, 0xd2, 0xff, 0x15, 0x0b, 0x1d, 0x4b, 0x2b, 0xd4, 0x30, 0xe2, 0x02, 0x30,
	0x51, 0xb6, 0x61, 0xee, 0xb8, 0x82, 0x78, 0x5f, 0x6d, 0x38, 0xb8, 0x57, 0x1d, 0xc9, 0x88, 0x1c,
	0xc3, 0x4e, 0x86, 0x22, 0x8f, 0xa5, 0xd1, 0x33, 0x15, 0xe9, 0x42, 0x6b, 0xc2, 0x79, 0x28, 0xb4,
	0xc8, 0x7e, 0x9f, 0x28, 0xef, 0xef, 0x15, 0x30, 0xd4, 0x17, 0x36, 0x92, 0x91, 0x5f, 0x10, 0x36,
	0x9a, 0x5c, 0x35, 0x3d, 0xdb, 0xff, 0x99, 0x9e, 0x35, 0xb3, 0x69, 0x6d, 0x3c, 0x1b, 0xef, 0x14,
	0xdc, 0x41, 0xbe, 0xbc, 0xff, 0xaa, 0xde, 0xa4, 0xca, 0xfe, 0xfc, 0x9f, 0x0c, 0xb5, 0x07, 0x1e,
	0xb4, 0x33, 0x14, 0x2c, 0xcc, 0x8d, 0x6b, 0x33, 0x95, 0x2a, 0xd6, 0x98, 0x53, 0xbb, 0x39, 0xa7,
	0xde, 0x4b, 0x78, 0xe1, 0x63, 0x54, 0x99, 0xbc, 0x4a, 0xa6, 0xea, 0x58, 0xb5, 0x93, 0xaf, 0x3b,
	0xdc, 0x74, 0x23, 0x1f, 0x6d, 0x85, 0xdd, 0xb0, 0x15, 0xde, 0x37, 0x1b, 0xc8, 0x63, 0x19, 0xd2,
	0x85, 0xc3, 0x90, 0x45, 0x11, 0x0b, 0xf2, 0x58, 0x2e, 0x2f, 0x70, 0x81, 0xb1, 0x71, 0xff, 0x10,
	0x56, 0x21, 0xa3, 0x0b, 0x2a, 0x69, 0xa6, 0xf5, 0xf7, 0x7c, 0x53, 0xa9, 0x07, 0x21, 0x65, 0xc1,
	0x6c, 0x44, 0x13, 0xd4, 0x71, 0xd9, 0xf3, 0x57, 0xb5, 0xfa, 0x26, 0x28, 0x9e, 0x8a, 0x62, 0xa5,
	0x4d, 0xa5, 0xf0, 0x5c, 0x60, 0x76, 0xb1, 0x30, 0x1b, 0x6c, 0x2a, 0xd2, 0x83, 0xfd, 0x0c, 0x6f,
	0x68, 0x16, 0xaa, 0xde, 0x84, 0x59, 0xd9, 0xb6, 0xba, 0x01, 0x26, 0x31, 0xb9, 0x4a, 0x99, 0xf4,
	0xab, 0x84, 0x52, 0xe7, 0x3c, 0x34, 0xab, 0x68, 0x2a, 0xd2, 0x81, 0xad, 0x2f, 0x7c, 0xec, 0xec,
	0x6a, 0x50, 0xfd, 0x54, 0x88, 0xc0, 0x5b, 0x67, 0xaf, 0x40, 0x04, 0xde, 0x7a, 0x97, 0x70, 0xb2,
	0x3e, 0x6b, 0x15, 0x65, 0xab, 0xa6, 0x5c, 0x75, 0x6b, 0xd7, 0xdd, 0x7a, 0x01, 0x1c, 0x96, 0x3a,
	0x4a, 0x43, 0x6d, 0xe6, 0x9a, 0xbc, 0x5b, 0x1b, 0xe7, 0x7d, 0xd0, 0xf9, 0x71, 0xe7, 0x5a, 0x3f,
	0xef, 0x5c, 0xeb, 0xd7, 0x9d, 0x6b, 0x7d, 0xff, 0xed, 0x3e, 0x19, 0xef, 0xe8, 0x77, 0xff, 0xcd,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0x7c, 0xba, 0x2e, 0x1d, 0x06, 0x00, 0x00,
}
